### ISSUE TITLE
[BUG] Ch4/01_OnePipeline_ManyClassifiers.ipynb missing sklearn import

### ISSUE THREAD

**Issue by mrneilsy** [practical-nlp/practical-nlp-code#83]
- Had to pip install sklearn. 
- Then edit the import of stop_words. Change to **_**stop_words
sklearn.feature_extraction import **_**stop_words
Google took me here > [https://stackoverflow.com/questions/68620436/cannot-import-name-stop-words-from-sklearn-feature-extraction](url)
- Then add the **_** later in the notebook. Section 2: Test Pre-processing
stopwords = **_**stop_words.ENGLISH_STOP_WORDS

**Comment by kartikay-bagla** [comment]
Hi. Can you share your Python and sklearn versions? I think this might be a deprecation issue.

**Comment by mrneilsy** [comment]
Python 3.8.10
sklearn 0.0 according to pip list which seems odd/wrong. It's whatever the current version is.

It does mention in the stackoverflow I linked that there was a change in a previous sklearn version

**Comment by kartikay-bagla** [comment]
Yep. That is odd. I just ran the notebook on Google Colab to double check and if you install the correct versions (listed in the first code cell of the notebook), you should be good to go.

**Comment by mrneilsy** [comment]
[initial import cell output.txt](https://github.com/practical-nlp/practical-nlp-code/files/7222102/initial.import.cell.output.txt)
Output from initial import attached. I see a note in the repo that you tested on Ubuntu / Python 3.6, I didn't see a recommended Python version in the book. I'll prob just stick with 3.8.10 and fix as I go. Good practice for me.
